### PR TITLE
Print numbers for scale

### PR DESCRIPTION
**Pull request by andrewcameronsims**
## Print numbers for scale

The Scatterplot object now generates an array of scale numbers on requests and can pass them to the Visualiser, which can print them to the screen using the method I have implemented called draw_y_axis_numbers. This could in principle be extended to x-axis though given that these are months at the moment it might not be appropriate.

Josh can you test this on your computer since I am having issues with my screen on this small device?

### CODE REVIEW

**Review by JoshTeperman — COMMENTED** [review]
This is nice:  `return variable_arr1.zip(variable_arr2)` . I knew .zip existed but couldn't remember the method name.

**Review by JoshTeperman — COMMENTED** [review]
Didn't quite get to the end of this, will check it on my machine first thing tomorrow. 
Good work today dude! This is a solid result for a day's work.

**Review by JoshTeperman — CHANGES_REQUESTED** [review]
Numbers are printing to screen, which is awesome, but it's not printing right. will slack you a screenshot. I assume you were still usint BOMWeatherdata.csv?

**Review by JoshTeperman — COMMENTED** [review]
I think we need to fix a bunch of the variable names before we ship this. Pretty difficult to follow I think for someone reading the code for the first time. Let's got over this together

**Comment by andrewcameronsims** [comment]
Fixed now, works.

**Review by JoshTeperman — APPROVED** [review]

**Pull request merged**
